name: Swift Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: macos-26

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: select xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: list schemes
        run: |
          xcodebuild -list

      - name: build and test with xcodebuild (macOS)
        run: |
          xcodebuild test \
            -scheme Gymnazo-Package \
            -destination 'platform=macOS,arch=arm64' \
            -parallel-testing-enabled NO
